### PR TITLE
Python3 support for b58digest method, just convert string to ascii bytes

### PR DESCRIPTION
**Pull request by dingus9**

### CODE REVIEW

**Comment by moreati** [comment]
How did you construct your Hash object? The `_digest` attribute should always be a byte string, E.g.

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subresource_integrity
>>> h = subresource_integrity.Hash.fromresource(b"qwertyuiop")
>>> h
subresource_integrity.Hash('sha384', 'SEcsiqdYRdPx/O8FpmB36Xyfrozgjc5/S3130p3lO9qyH6zjlRjmoLzNhK268cTX', '')
>>> h.b58digest
'SEcsiqdYRdPx/O8FpmB36Xyfrozgjc5/S3130p3lO9qyH6zjlRjmoLzNhK268cTX'
>>> h.digest
b'HG,\x8a\xa7XE\xd3\xf1\xfc\xef\x05\xa6`w\xe9|\x9f\xae\x8c\xe0\x8d\xce\x7fK}w\xd2\x9d\xe5;\xda\xb2\x1f\xac\xe3\x95\x18\xe6\xa0\xbc\xcd\x84\xad\xba\xf1\xc4\xd7'
```

**Comment by dingus9** [comment]
Hey yeah so things work if you use all of the generator methods however I'm in a situation where I'm initializing a Hash object direction from a raw pregenerated sha256 hash string... and need to pump it into a Hash object. Calling the Hash's .__init__() seemed to be a reasonable way to do so. I'm using the formatting str(my_hash_obj) syntax to dump the appropriately formatted SRI values later.
```
integrity.Hash('sha256', 'e1bc6bb39deff4ce2889b7375ec41bcf659fe40084c1a15ce05927218f64e44f')
```

I suppose it would be easy to require a bytes value as input to __init__, but having one allow a field of a string(algorithm) and the other require a bytes(implicitly) is odd especially when the hash value coming in from input is valid as a string. A side note is, in 2.x base64.encode allows the input to be a string, but in 3.x the encode requires a bytes.

I supposed the question would be, should the library require the hash value to be a bytes; if so then I can would suggest an assert isinstance(hash_value, bytes) in the __init__ OR should it just fail when used later(current behavior) This makes it (a little more) difficult to troubleshoot as it doesn't currently tell the user to format as a bytes when creating a Hash class and seems to work up to the point when you attempt to repr or str the object.

For usability I'd recommend just accepting a string or bytes and converting before sending to the encode method.

Thanks

**Comment by moreati** [comment]
> integrity.Hash('sha256', 'e1bc6bb39deff4ce2889b7375ec41bcf659fe40084c1a15ce05927218f64e44f')

The digest argument to `Hash()` is meant to be a bytes object, because it should contain the unmodified output of the hash function (e.g. a value obtained from `hashlib.sha256(b'hello').digest()`). What you have above is a _hex encoded_ digest, which is not the correct was to call `Hash()`.

Sorry for the confusion, the constructor is dire need of some documentation and input checking.

> I supposed the question would be, should the library require the hash value to be a bytes; if so then I can would suggest an `assert isinstance(hash_value, bytes)`

I have some commits incoming that will raise a `TypeError`. Along with other API cleanups, and expanded docstring coverage.

> For usability I'd recommend just accepting a string or bytes and converting before sending to the encode method.

I'm not keen on this. The `Hash.fromhash()` constructor covers construction from a base58 encoded hash. I don't like overloading the meaning/interpretation of an argument.

**Comment by dingus9** [comment]
Then it should not accept a string as input. And how would you recommend
this be used for hashes coming from the command line?

**Comment by moreati** [comment]
I've added type checking to `Hash.__init__()` and added docstrings to describe what types are expected for the arguments. The new version is on PyPI https://pypi.org/project/subresource-integrity/0.2/.

If you want a way to construct a `Hash` object from a hex-encoded digest, I would be open to a PR that adds a `Hash.fromhexdigest()` class method.

**Pull request closed without merging**
